import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(fileURLToPath(import.meta.url));

export function createBrowserBundle() {
  const localeDirectory = path.join(root, "locales");
  const staticLocales = Object.fromEntries(
    fs.readdirSync(localeDirectory)
      .filter((file) => file.endsWith(".json"))
      .sort()
      .map((file) => [
        path.basename(file, ".json"),
        JSON.parse(fs.readFileSync(path.join(localeDirectory, file), "utf8")),
      ])
  );
  const i18nSource = fs
    .readFileSync(path.join(root, "i18n.js"), "utf8")
    .replace(/^export\s+(const|function)\s+/gm, "$1 ");
  const markdownSource = fs
    .readFileSync(path.join(root, "markdown.js"), "utf8")
    .replace(/^export\s+(const|function)\s+/gm, "$1 ");
  const appSource = fs
    .readFileSync(path.join(root, "script.js"), "utf8")
    .replace(/^import\s+\{[^\n]+\}\s+from\s+"\.\/(?:i18n|markdown)\.js";\s*$/gm, "");

  return `/* Generated by build-browser.js. Do not edit directly. */\n(() => {\n  "use strict";\nconst STATIC_LOCALES = Object.freeze(${JSON.stringify(staticLocales)});\n${i18nSource}\n${markdownSource}\n${appSource}\n})();\n`;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  fs.writeFileSync(path.join(root, "app.js"), createBrowserBundle());
}
